# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('price_bought', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date_bought', models.DateTimeField()),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date_sold', models.DateTimeField()),
            ],
        ),
    ]
