# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradetracker', '0002_auto_20161116_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_type',
        ),
        migrations.AddField(
            model_name='trade',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
