# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradetracker', '0003_auto_20161117_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(),
        ),
    ]
